### ISSUE TITLE
timeline or to do list

### ISSUE THREAD

**Issue by cuijh26** [IGLICT/SketchDream#1]
@ty625911724 Great work! I want to know when will you release the code? I am eager to have a try! thanks!

**Comment by ty625911724** [comment]
Thanks a lot for your attention. We will release the code before June 30th.

**Comment by ChuXiaoyuu** [comment]
Hi,  it's already July. 🥺🥺🥺

**Comment by ech0-7** [comment]
Where is the sketch data comes from?

**Comment by ty625911724** [comment]
We use this method to extract sketches. https://github.com/carolineec/informative-drawings

We will release the code as soon as possible.
