### ISSUE TITLE
Dataset Problem

### ISSUE THREAD

**Issue by HyoraMeteor** [IGLICT/SketchDream#13]
Wonderful work! I noticed that your data format ("recon_dataset" in threestudio) is different from the other NeRF datasets I have found. How should I run your pipeline using my own multi-view images or mesh? Especially to get reconstruction checkpoints.

**Comment by ty625911724** [comment]
I am sorry that we do not use stardard NeRF rendering format. We have provided the blender rendering scripts in `tools/blender_script_SketchDream.py`.

**Comment by HyoraMeteor** [comment]
Thank you so much for the reply!
